"""
Django settings for MALEYANGA project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# ⭐ CORREÇÃO: .parent.parent.parent para apontar para MALEYANGA/
# BASE_DIR = Path(__file__).resolve().parent.parent.parent
# ⭐ CORREÇÃO DEFINITIVA - Adicione no settings.py:
# ⭐ CORREÇÃO DEFINITIVA - Use caminho absoluto
# ⭐ USE ESTE CAMINHO ABSOLUTO NO settings.py:
BASE_DIR = Path(__file__).resolve().parent.parent  # backend/

# ⭐ Verificação de caminho (pode remover depois)
print(f"⭐ DEBUG: BASE_DIR = {BASE_DIR}")
print(f"⭐ DEBUG: Templates path = {BASE_DIR / 'templates'}")

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-u)ajw51ed!%8c^$n$odr#j(=8-(5b_x03c!cn4xmn&cl&j=1ur'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MALEYANGA.urls'

# ⭐ CONFIGURAÇÃO CORRIGIDA DOS TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # backend/templates/
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # ⭐ DEVE ESTAR
                'django.contrib.auth.context_processors.auth',  # ⭐ DEVE ESTAR
                'django.contrib.messages.context_processors.messages',  # ⭐ DEVE ESTAR
            ],
        },
    },
]

WSGI_APPLICATION = 'MALEYANGA.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # ⭐ CORRETO: backend/db.sqlite3
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ⭐ Static files (CONFIGURAÇÃO CORRIGIDA)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / '..' / 'static',  # ⭐ Agora aponta para MALEYANGA/static/
]
# ⭐ VERIFIQUE SE A PASTA STATIC EXISTE, SE NÃO, CRIE:
static_dir = BASE_DIR / '..' / 'static'
if not static_dir.exists():
    print(f"⭐ AVISO: Criando pasta static em {static_dir}")
    static_dir.mkdir(exist_ok=True)

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ⭐ Configuração Vite melhorada
VITE_DEV_MODE = DEBUG
# settings.py
if DEBUG:
    # Configurações de desenvolvimento
    VITE_DEV_SERVER_URL = 'http://localhost:3000'
    template_js = f'{VITE_DEV_SERVER_URL}/src/main.jsx'
else:
    # Configurações de produção
    template_js = '/static/dist/assets/index-BfkMANgE.js'

if VITE_DEV_MODE:
    VITE_DEV_SERVER_URL = 'http://localhost:3000'
    # ⭐ CORS para desenvolvimento
    INSTALLED_APPS += ['corsheaders']
    MIDDLEWARE.insert(0, 'corsheaders.middleware.CorsMiddleware')
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
else:
    VITE_DEV_SERVER_URL = ''
