# Generated by Django 5.2.6 on 2025-09-07 12:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome Completo')),
                ('nuit', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='NUIT')),
                ('tipoDeIdentificacao', models.CharField(blank=True, choices=[('BI', 'BI'), ('Passaporte', 'Passaporte'), ('Carta de conducao', 'Carta de condução'), ('Outro', 'Outro')], max_length=255, null=True, verbose_name='Tipo de Identificação')),
                ('numeroDeIdentificacao', models.CharField(max_length=255, verbose_name='Número de Identificação')),
                ('residencia', models.CharField(max_length=255, verbose_name='Residência')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('localDeTrabalho', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Trabalho')),
                ('telefone', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter exatamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('telefone1', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter exatamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('telefone2', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter exatamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('estadoCivil', models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Solteira', 'Solteira'), ('Casado', 'Casado'), ('Casada', 'Casada'), ('Separado Judicialmente', 'Separado Judicialmente'), ('Separada Judicialmente', 'Separada Judicialmente'), ('Outro', 'Outro')], max_length=255, null=True, verbose_name='Estado Civil')),
                ('dataDeExpiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('dataDeEmissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('codigo', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Código do Cliente')),
                ('nomeDoArquivoDeIdentificacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo de Identificação')),
                ('nacionalidade', models.CharField(blank=True, max_length=255, null=True)),
                ('dataDeNascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('profissao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profissão')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'masculino'), ('feminino', 'feminino'), ('transgenero', 'transgênero'), ('nao-binario', 'não-binário'), ('agenero', 'agênero'), ('pangenero', 'pangênero'), ('genderqueer', 'genderqueer'), ('two-spirit', 'two-spirit'), ('outro', 'outro')], max_length=255, null=True, verbose_name='Gênero')),
                ('classificacao', models.CharField(blank=True, choices=[('excelente', 'excelente'), ('bom', 'bom'), ('medio', 'medio'), ('mau', 'mau'), ('pessimo', 'pessimo')], default='medio', max_length=255, null=True, verbose_name='Classificação')),
                ('ativo', models.BooleanField(default=True)),
                ('emDivida', models.BooleanField(default=False, verbose_name='Em Dívida')),
                ('totalEmDivida', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total em Dívida')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome Completo')),
                ('nuit', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='NUIT')),
                ('tipoDeIdentificacao', models.CharField(blank=True, choices=[('BI', 'BI'), ('Passaporte', 'Passaporte'), ('Carta de conducao', 'Carta de condução'), ('Outro', 'Outro')], max_length=255, null=True, verbose_name='Tipo de Identificação')),
                ('numeroDeIdentificacao', models.CharField(max_length=255, verbose_name='Número de Identificação')),
                ('residencia', models.CharField(max_length=255, verbose_name='Residência')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('localDeTrabalho', models.CharField(blank=True, max_length=255, null=True, verbose_name='Local de Trabalho')),
                ('telefone', models.CharField(blank=True, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter exatamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('telefone1', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter exatamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('telefone2', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='O número de telefone deve ter exatamente 9 dígitos.', regex='^[0-9]{9}$')])),
                ('estadoCivil', models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Solteira', 'Solteira'), ('Casado', 'Casado'), ('Casada', 'Casada'), ('Separado Judicialmente', 'Separado Judicialmente'), ('Separada Judicialmente', 'Separada Judicialmente'), ('Outro', 'Outro')], max_length=255, null=True, verbose_name='Estado Civil')),
                ('dataDeExpiracao', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('dataDeEmissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assinantes', to='clientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Assinante',
                'verbose_name_plural': 'Assinantes',
            },
        ),
    ]
