# Generated by Django 5.2.6 on 2025-09-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinante',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='assinantes',
            field=models.ManyToManyField(related_name='clientes', to='clientes.assinante', verbose_name='Assinantes'),
        ),
    ]
