# Generated by Django 5.2.6 on 2025-09-09 13:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_assinante_telefone_alter_assinante_telefone1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_creditado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_concecao', models.DateField()),
                ('moras', models.IntegerField(default=0)),
                ('validade', models.DateField(blank=True, null=True)),
                ('numero_do_credito', models.CharField(max_length=50)),
                ('percentual_de_juros', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('percentual_juros_de_demora', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('total_da_divida_sem_moras', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_em_divida', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('total_moras', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('taxas', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('Aberto', 'Aberto'), ('Pendente', 'Pendente'), ('Fechado', 'Fechado'), ('EmProgresso', 'Em Progresso')], default='Aberto', max_length=20)),
                ('forma_de_calculo', models.CharField(choices=[('pmt', 'PMT'), ('taxafixa', 'Taxa Fixa')], max_length=20)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('quinzenal', 'Quinzenal'), ('semanal', 'Semanal'), ('diario', 'Diário'), ('doisdias', 'Dois Dias'), ('variavel', 'Variável')], max_length=20)),
                ('em_divida', models.BooleanField(default=True)),
                ('invalido', models.BooleanField(default=False)),
                ('numero_de_prestacoes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recorencia_de_moras', models.IntegerField(blank=True, null=True)),
                ('reter_capital', models.BooleanField(default=False)),
                ('valor_de_juros', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('em_mora', models.BooleanField(default=False)),
                ('periodo_variavel', models.IntegerField(blank=True, null=True)),
                ('ignorar_valor_pago_no_prazo', models.BooleanField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('numero_de_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_da_prestacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_de_juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_pago_juros', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_de_amortizacao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_pago_amortizacao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('total_pago_no_prazo', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('total_em_divida', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('total_em_divida_sem_moras', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_de_juros_de_demora', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_pago_demora', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_da_remissao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('dias_de_mora', models.IntegerField(default=0)),
                ('recorencia_de_moras', models.IntegerField(default=1)),
                ('pago', models.BooleanField(default=False)),
                ('valores_alocados', models.BooleanField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_de_pagamento', models.DateField(blank=True, null=True)),
                ('data_previsto_de_pagamento', models.DateField(blank=True, null=True)),
                ('data_da_criacao', models.DateField(blank=True, null=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='creditos.credito')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['data_previsto_de_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_do_recibo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_parcial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('valor_pago_backup', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('data_de_pagamento', models.DateField()),
                ('nome_do_cliente', models.CharField(default='', max_length=200)),
                ('forma_de_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência'), ('cheque', 'Cheque'), ('mbway', 'MBWay'), ('multibanco', 'Multibanco')], max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('invalido', models.BooleanField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='creditos.pagamento')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
                'ordering': ['-data_de_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='Remissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_da_remissao', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remissoes', to='creditos.pagamento')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remissão',
                'verbose_name_plural': 'Remissões',
                'ordering': ['-created_date'],
            },
        ),
    ]
